export const books = [
  {
    _id: "b1",
    sku: "BK-ENG-601",
    title: "Popy English For Today",
    author: "Popy Publications",
    category: "HSC",
    tag: "New",
    format: "Print",
    price: 575,
    stock: 120,
    status: "in_stock",
  },
  {
    _id: "b2",
    sku: "BK-BAN-214",
    title: "HSC Bangla Literature Anthology",
    author: "Dr. Muhammed Zafar Iqbal",
    category: "HSC",
    tag: "Best Seller",
    format: "Print",
    price: 420,
    stock: 35,
    status: "low_stock",
  },
  {
    _id: "b3",
    sku: "BK-BCS-510",
    title: "BCS Question Bank",
    author: "Notion Press",
    category: "BCS",
    tag: "Focus Series",
    format: "Print",
    price: 690,
    stock: 0,
    status: "out_of_stock",
  },
  {
    _id: "b4",
    sku: "BK-SCI-320",
    title: "Science Olympiad Playbook",
    author: "Chotoder Biggan",
    category: "Academic",
    tag: "Academic",
    format: "Print",
    price: 480,
    stock: 52,
    status: "in_stock",
  },
  {
    _id: "b5",
    sku: "BK-ENG-430",
    title: "English Grammar Plus",
    author: "Popy Publications",
    category: "Secondary",
    tag: "Popular",
    format: "Print",
    price: 399,
    stock: 18,
    status: "low_stock",
  },
  {
    _id: "b6",
    sku: "BK-SSC-605",
    title: "SSC Model Test Pack",
    author: "Board Experts",
    category: "SSC",
    tag: "Hot",
    format: "Print",
    price: 650,
    stock: 94,
    status: "in_stock",
  },
  {
    _id: "b7",
    sku: "BK-BAN-332",
    title: "Bangla Grammar Guide",
    author: "Popy Publications",
    category: "Secondary",
    tag: "Recommended",
    format: "Print",
    price: 310,
    stock: 8,
    status: "low_stock",
  },
  {
    _id: "b8",
    sku: "BK-MATH-215",
    title: "Math Practice Guide",
    author: "Popy Publications",
    category: "Primary",
    tag: "Practice",
    format: "Print",
    price: 350,
    stock: 65,
    status: "in_stock",
  },
  {
    _id: "b9",
    sku: "BK-GEO-508",
    title: "Geography Atlas",
    author: "Map House",
    category: "Secondary",
    tag: "New Edition",
    format: "Print",
    price: 450,
    stock: 0,
    status: "out_of_stock",
  },
  {
    _id: "b10",
    sku: "BK-LIT-412",
    title: "Creative Writing Workbook",
    author: "Writers Guild",
    category: "Secondary",
    tag: "Workbook",
    format: "Print",
    price: 280,
    stock: 47,
    status: "in_stock",
  },
];