export const users = [
    {
        _id: "1",
        name: "John Doe",
        email: "john.doe@example.com",
        phone_number: "1234567890",
        company_id: "1234567890",
        status: "active",
        role: "EMPLOYER",
        is_block: false,
    },
    {
        _id: "2",
        name: "Jane Smith",
        email: "jane.smith@example.com",
        phone_number: "1234567890",
        company_id: "1234567890",
        status: "active",
        role: "EMPLOYER",
        is_block: true,
    },
    {
        _id: "3",
        name: "John Doe 2",
        email: "john.doe@example.com",
        phone_number: "1234567890",
        company_id: "1234567890",
        status: "active",
        role: "EMPLOYER",
        is_block: false,
    },
    {
        _id: "4",
        name: "John Doe 3",
        email: "john.doe@example.com",
        phone_number: "1234567890",
        company_id: "1234567890",
        status: "active",
        role: "EMPLOYER",
        is_block: false,
    },
    {
        _id: "5",
        name: "John Doe 4",
        email: "john.doe@example.com",
        phone_number: "1234567890",
        company_id: "1234567890",
        status: "active",
        role: "EMPLOYER",
        is_block: false,
    },
    {
        _id: "6",
        name: "John Doe 5",
        email: "john.doe@example.com",
        phone_number: "1234567890",
        company_id: "1234567890",
        status: "active",
        role: "EMPLOYER",
        is_block: false,
    },
    {
        _id: "7",
        name: "John Doe 6",
        email: "john.doe@example.com",
        phone_number: "1234567890",
        company_id: "1234567890",
        status: "active",
        role: "EMPLOYER",
        is_block: false,
    },
    {
        _id: "8",
        name: "John Doe 7",
        email: "john.doe@example.com",
        phone_number: "1234567890",
        company_id: "1234567890",
        status: "active",
        role: "EMPLOYER",
        is_block: false,
    },
    {
        _id: "9",
        name: "John Doe 8",
        email: "john.doe@example.com",
        phone_number: "1234567890",
        company_id: "1234567890",
        status: "active",
        role: "EMPLOYER",
        is_block: false,
    },
    {
        _id: "10",
        name: "John Doe 9",
        email: "john.doe@example.com",
        phone_number: "1234567890",
        company_id: "1234567890",
        status: "active",
        role: "EMPLOYER",
        is_block: false,
    }
];