export const categories = [
  {
    _id: "c1",
    name: "Play Group & Nursery",
    slug: "play-group-nursery",
    parent: null,
    parentName: null,
    bookCount: 24,
    visibility: "public",
    status: "active",
    createdAt: "2024-12-10T09:00:00Z",
  },
  {
    _id: "c2",
    name: "KG & Class One",
    slug: "kg-class-one",
    parent: null,
    parentName: null,
    bookCount: 18,
    visibility: "public",
    status: "active",
    createdAt: "2024-12-12T11:30:00Z",
  },
  {
    _id: "c3",
    name: "Primary (Class Two-Five)",
    slug: "primary-class-two-five",
    parent: null,
    parentName: null,
    bookCount: 36,
    visibility: "public",
    status: "active",
    createdAt: "2024-12-14T08:45:00Z",
  },
  {
    _id: "c4",
    name: "Junior Secondary (Class Six-Eight)",
    slug: "junior-secondary",
    parent: null,
    parentName: null,
    bookCount: 28,
    visibility: "internal",
    status: "active",
    createdAt: "2024-12-18T10:15:00Z",
  },
  {
    _id: "c5",
    name: "Secondary (Class Nine-SSC)",
    slug: "secondary-ssc",
    parent: null,
    parentName: null,
    bookCount: 31,
    visibility: "public",
    status: "active",
    createdAt: "2024-12-20T14:05:00Z",
  },
  {
    _id: "c6",
    name: "Higher Secondary (HSC)",
    slug: "hsc",
    parent: null,
    parentName: null,
    bookCount: 22,
    visibility: "public",
    status: "active",
    createdAt: "2024-12-22T09:40:00Z",
  },
  {
    _id: "c7",
    name: "BCS",
    slug: "bcs",
    parent: null,
    parentName: null,
    bookCount: 12,
    visibility: "public",
    status: "active",
    createdAt: "2024-12-24T13:20:00Z",
  },
  {
    _id: "c8",
    name: "University Admission",
    slug: "admission",
    parent: null,
    parentName: null,
    bookCount: 15,
    visibility: "public",
    status: "draft",
    createdAt: "2024-12-26T16:50:00Z",
  },
  {
    _id: "c9",
    name: "Olympiad",
    slug: "olympiad",
    parent: "secondary-ssc",
    parentName: "Secondary (Class Nine-SSC)",
    bookCount: 9,
    visibility: "internal",
    status: "active",
    createdAt: "2024-12-28T12:25:00Z",
  },
];